/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

interface LatticeDynamics {
  void LatticeDynamics(double d, Potential p, boolean doLRC, long nBasis);
  long getStatus();
  void setNumCells(long x, long y, long z);
  void setUnitCell(double x, double y, double z);
  void setBasis(long i, double x, double y, double z);
  void setup();
  long goLS(long nMax);
  long countLS();
  long doSelfSum();
  long goEVD(long nwv);
  long getWaveVectorCount();
  boolean getUnstable();
  double getU();
  double getLogSum();
  VoidPtr getEigenvalues();
};

