interface Potential {
  void setCutoff(double rc);
  double getCutoff();
  void setTruncationType(long tt);
  long getTruncationType();
};

interface PotentialLJ : Potential {
  void PotentialLJ(double epsilon, double sigma, long tt, double rc);
};

PotentialLJ implements Potential;

interface PotentialSS : Potential {
  void PotentialSS(double epsilon, long p, long tt, double rc);
};

PotentialSS implements Potential;

interface PotentialWCA : PotentialLJ {
  void PotentialWCA(double epsilon, double sigma);
};

PotentialWCA implements PotentialLJ;

interface PotentialHS : Potential {
  void PotentialHS(double sigma);
};

PotentialHS implements Potential;

[JSImplementation="Potential"]
interface PotentialJS {
  void PotentialJS();
  double u(double r2);
  double du(double r2);
  double d2u(double r2);
};

interface SpeciesList {
  void SpeciesList();
  long size();
  void add(Species species);
  Species get(long iSpecies);
};

interface Species {
  long getNumAtoms();
  VoidPtr getAtomTypes();
};

interface SpeciesSimple : Species {
  void SpeciesSimple(long numAtoms, double mass);
};

SpeciesSimple implements Species;

interface Box {
  void Box([Ref] SpeciesList speciesList);
  long getNumAtoms();
  long getNumMolecules(long iSpecies);
  long getTotalNumMolecules();
  void setNumMolecules(long iSpecies, long numMolecules);
  [Const] VoidPtr getBoxSize();
  void setBoxSize(double x, double y, double z);
  void initCoordinates();
  VoidPtr getAtomPosition(long iAtom);
  void enableVelocities();
  VoidPtr getAtomVelocity(long iAtom);
};

interface PotentialMaster {
  void PotentialMaster([Ref] SpeciesList sl, [Ref] Box box);
  void setPairPotential(long iType, long jType, Potential pij);
  void setDoTruncationCorrection(boolean doCorrection);
};

interface PotentialMasterCell : PotentialMaster {
  void PotentialMasterCell([Ref] SpeciesList sl, [Ref] Box box, long cellRange);
  void init();
};

PotentialMasterCell implements PotentialMaster;

interface PotentialMasterList : PotentialMasterCell {
  void PotentialMasterList([Ref] SpeciesList sl, [Ref] Box box, long cellRange, double nbrRange);
};

PotentialMasterList implements PotentialMasterCell;

interface PotentialMasterVirial : PotentialMaster {
  void PotentialMasterVirial([Ref] SpeciesList sl, [Ref] Box box);
};

PotentialMasterVirial implements PotentialMaster;

interface Random {
  void Random();
  void Random(long seed);
  long getSeed();
};

interface MCMove {
  double getAcceptance();
  attribute double stepSize;
  attribute boolean tunable;
  attribute boolean verboseAdjust;
};

interface MCMoveDisplacement : MCMove {
  void MCMoveDisplacement([Ref] Box box, [Ref] PotentialMaster potentialMaster, [Ref] Random random, double stepSize);
};

MCMoveDisplacement implements MCMove;

interface MCMoveInsertDelete : MCMove {
  void MCMoveInsertDelete([Ref] Box box, [Ref] PotentialMaster potentialMaster, [Ref] Random random, double mu, long iSpecies);
};

MCMoveInsertDelete implements MCMove;

interface MCMoveDisplacementVirial : MCMove {
  void MCMoveDisplacementVirial([Ref] Box box, [Ref] PotentialMaster potentialMaster, [Ref] Random random, double stepSize, [Ref] Cluster cluster);
};

MCMoveDisplacementVirial implements MCMove;

interface MCMoveChainVirial : MCMove {
  void MCMoveChainVirial([Ref] Box box, [Ref] PotentialMaster potentialMaster, [Ref] Random random, double sigma);
};

MCMoveDisplacementVirial implements MCMove;

interface IntegratorListener { };

interface DataSink { };

interface Average : DataSink {
  void Average(long nData, long blockSize, long maxBlockCount, boolean doCovariance);
  void setNumData(long newNumData);
  VoidPtr getStatistics();
  VoidPtr getBlockCovariance();
  void reset();
};

Average implements DataSink;

interface Meter {
  long getNumData();
  VoidPtr getData();
};

interface PotentialCallback { };

interface PotentialCallbackPressure : PotentialCallback {
  void PotentialCallbackPressure([Ref] Box box, double temperature);
};

PotentialCallbackPressure implements PotentialCallback;

interface PotentialCallbackHMA : PotentialCallback {
  void PotentialCallbackHMA([Ref] Box box, double temperature, double Pharm);
};

PotentialCallbackHMA implements PotentialCallback;

interface MeterPotentialEnergy : Meter {
  void MeterPotentialEnergy([Ref] Integrator integrator);
};

MeterPotentialEnergy implements Meter;

interface MeterKineticEnergy : Meter {
  void MeterKineticEnergy([Ref] Box box);
  void setIntegrator(Integrator integrator);
};

MeterKineticEnergy implements Meter;

interface MeterFullCompute : Meter {
  void MeterFullCompute([Ref] PotentialMaster potentialMaster);
  void addCallback(PotentialCallback pcb);
  void setDoCompute(boolean doCompute);
};

MeterFullCompute implements Meter;

interface MeterNumAtoms : Meter {
  void MeterNumAtoms([Ref] Box box);
};

MeterNumAtoms implements Meter;

interface MeterDensity : Meter {
  void MeterDensity([Ref] Box box);
};

MeterDensity implements Meter;

interface DataPump : IntegratorListener {
  void DataPump([Ref] Meter meter, long interval);
  void DataPump([Ref] Meter meter, long interval, DataSink sink);
  DataSink getDataSink(long i);
};

DataPump implements IntegratorListener;

interface Integrator {
  void doStep();
  void doSteps(long steps);
  void setTemperature(double temperature);
  double getTemperature();
  void reset();
  double getPotentialEnergy();
  void addListener(IntegratorListener listener);
  long getStepCount();
};

interface IntegratorMC : Integrator {
  void IntegratorMC([Ref] PotentialMaster potentialMaster, [Ref] Random random);
  void addMove(MCMove move, double moveProb);
  void removeMove(MCMove move);
  void setTuning(boolean doTuning);
};

IntegratorMC implements Integrator;

interface IntegratorMD : Integrator {
  void IntegratorMD([Ref] PotentialMaster potentialMaster, [Ref] Random random, [Ref] Box box);
  void setTimeStep(double tStep);
  void setNbrCheckInterval(long interval);
  void addPotentialCallback(PotentialCallback pc, long interval);
};

IntegratorMD implements Integrator;

interface Cluster { };

interface ClusterVirial : Cluster {
  void ClusterVirial([Ref] PotentialMasterVirial potentialMaster, double temperature, long nDer, boolean cached);
};

ClusterVirial implements Cluster;

interface ClusterChain : Cluster {
  void ClusterChain([Ref] PotentialMasterVirial potentialMaster, double tempreature, double chainFac, double ringFac);
};

ClusterVirial implements Cluster;

interface VirialAlpha {
  void VirialAlpha([Ref] IntegratorMC refIntegrator, [Ref] IntegratorMC targetIntegrator,
                   [Ref] Cluster refClusterRef, [Ref] Cluster refClusterTarget,
                   [Ref] Cluster targetClusterRef, [Ref] Cluster targetClusterTarget);
  void setVerbose(boolean newVerbose);
  void runSteps(long steps);
  VoidPtr getAlphaStatistics();
  boolean getAllDone();
};

interface VirialProduction {
  void VirialProduction([Ref] IntegratorMC refIntegrator, [Ref] IntegratorMC targetIntegrator,
                   [Ref] Cluster refClusterRef, [Ref] Cluster refClusterTarget,
                   [Ref] Cluster targetClusterRef, [Ref] Cluster targetClusterTarget,
                   double alpha, double refIntegral);
  void runSteps(long numSteps);
  VoidPtr getFullStats();
  VoidPtr getAlphaStats();
  VoidPtr getRefStats();
  VoidPtr getTargetStats();
  VoidPtr getRefBCStats();
  VoidPtr getTargetBCStats();
  VoidPtr getRefRatioStats();
  VoidPtr getTargetRatioStats();
};
  

interface ArrayUtil {
  void ArrayUtil(VoidPtr p);
  double x(long i);
  double x2d(long i, long j);
};
